replicaCount: 1
namespace: misp

web:
  repository: floatingghost/misp-k8s
  tag: latest
  pullPolicy: Always

config:
  baseurl: https://misp.local
  server_name: misp.local
  admin_email: admin@misp.local
  admin_passphrase: aaaa
  timezone: Europe/London

  mysql:
    host: my.sql
    password: abcd

  # For sessions. Leave as-is unless you know what you're doing
  redis_connection_string: tcp://redis:6379/1

  # Internal MISP config
  # Will set config keys, i.e MISP.live
  appconfig: |
      MISP:
        live: true
        redis_host: redis
        redis_port: 6379
        redis_database: 13
        org: ORGNAME
        baseurl: "https://misp.local"
        attachments_dir: "s3://"

      Security:
        salt: ChangeMe

      Plugin:
        S3_enable: true
        S3_bucket_name: 'my-s3-bucket'
        S3_region: eu-west-1

service:
  type: NodePort
  port: 80

redis:
  enabled: true
  image: redis
  tag: latest
  pullPolicy: IfNotPresent

