# Default values for misp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: misp

web:
  repository: floatingghost/misp-k8s
  tag: latest
  pullPolicy: IfNotPresent
  MISP_BASEURL: http://misp.local
  SERVERNAME: misp.local
  MISP_ADMIN_EMAIL: admin@misp.local
  MISP_ADMIN_PASSPHRASE: goodpassworD!1
  MYSQL_HOST: mysql://my.sql
  MYSQL_MISP_PASSWORD: misp
  # Leave as redis unless you disable redis below and want a shared server
  REDIS_CONNECTION_STRING: redis://redis
  # Share across pods for password stuff y'know
  PASSWORD_SALT: haha_YES
  ORGNAME: MyOrganization
  TIMEZONE: UTC
  

service:
  type: NodePort
  port: 80

redis:
  enabled: false
  image: redis
  tag: latest
  pullPolicy: IfNotPresent

