{{- if .Values.redis.enabled }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "misp.fullname" . }}-redis
  labels:
    app: redis
    chart: {{ template "misp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: redis
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}:{{ .Values.redis.tag }}"
          ports:
            - containerPort: 6379
              targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: {{ template "misp.name" . }}-redis
    chart: {{ template "misp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: redis
    release: {{ .Release.Name }}
{{- end}}
