---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "misp.fullname" . }}
  labels:
    app: {{ template "misp.name" . }}
    chart: {{ template "misp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "misp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "misp.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.repository }}:{{ .Values.web.tag }}"
          imagePullPolicy: {{ .Values.web.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: MISP_BASEURL
            value: {{ .Values.config.baseurl }}
          - name: MYSQL_HOST
            value: {{ .Values.config.mysql.host }}
          - name: MYSQL_MISP_PASSWORD
            value: {{ .Values.config.mysql.password }}
          - name: TIMEZONE
            value: {{ .Values.web.TIMEZONE }}
          - name: SERVERNAME
            value: {{ .Values.config.server_name }}
          - name: REDIS_CONNECTION_STRING
            value: {{ .Values.config.redis_connection_string }}
          volumeMounts:
          - name: config
            mountPath: /config
      volumes:
      - name: config
        configMap:
          name: {{ template "misp.fullname" . }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "misp.fullname" . }}
  labels:
    app: {{ template "misp.name" . }}
    chart: {{ template "misp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
#  sessionAffinity: ClientIP
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 10800

  type: {{ .Values.web.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "misp.name" . }}
    release: {{ .Release.Name }}
