---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "misp.fullname" . }}
  labels:
    app: {{ template "misp.name" . }}
    chart: {{ template "misp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "misp.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "misp.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.repository }}:{{ .Values.web.tag }}"
          imagePullPolicy: {{ .Values.web.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          {{- if .Values.config.pgp.from_s3 }}
          - name: PGP_S3
            value: {{ .Values.config.pgp.s3_url }}
          {{- else }}
          - name: MISP_ADMIN_EMAIL
            value: {{ .Values.config.admin_email }}
          - name: MISP_ADMIN_PASSPHRASE
            value: {{ .Values.config.admin_passphrase }}
          {{- end }}

          - name: MISP_BASEURL
            value: {{ .Values.config.baseurl }}
          - name: MYSQL_HOST
            value: {{ .Values.config.mysql.host }}
          - name: MYSQL_MISP_PASSWORD
            value: {{ .Values.config.mysql.password }}
          - name: POSTFIX_EXTRA_CONFIG
            value: {{ .Values.config.postfix.extra_config | quote }}
          - name: TIMEZONE
            value: {{ .Values.config.timezone }}
          - name: POSTFIX_RELAY_HOST
            value: {{ .Values.config.postfix.relay_host | quote}}
          - name: SMTP_USERNAME
            value: {{ .Values.config.postfix.smtp.username }}
          - name: SMTP_PASSWORD
            value: {{ .Values.config.postfix.smtp.password }}
          - name: SERVERNAME
            value: {{ .Values.config.server_name }}
          - name: REDIS_CONNECTION_STRING
            value: {{ .Values.config.redis_connection_string }}
          volumeMounts:
          - name: config
            mountPath: /config
      volumes:
      - name: config
        configMap:
          name: {{ template "misp.fullname" . }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "misp.fullname" . }}
  labels:
    app: {{ template "misp.name" . }}
    chart: {{ template "misp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
#  sessionAffinity: ClientIP
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 10800

  type: {{ .Values.web.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "misp.name" . }}
    release: {{ .Release.Name }}
